import {
  Home,
  MessageSquare,
  Calendar,
  Users,
  FolderOpen,
  BookOpen,
  FileText,
  UserCheck,
  Building,
  Settings,
  HelpCircle,
  ChevronLeft,
  BarChart3,
  Sun,
  Bell,
  Grid3X3,
  TrendingUp,
  TrendingDown,
  Coffee,
  Phone,
  Monitor,
  DollarSign,
  Crown,
  Shield,
  X,
  Bot,
  Megaphone,
  Users2,
  Star,
  ArrowUp,
  ArrowDown,
  Play,
  ImageIcon,
  Video,
  FileTextIcon,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Youtube,
  Mail,
  Briefcase,
  BarChart,
  Eye,
  Calculator,
  ShieldCheck,
  List,
  MegaphoneIcon,
  Search,
  Filter,
  Edit,
  Clock,
  Award,
  GraduationCap,
  Zap,
  TrendingUpIcon,
  UserPlus,
  Download,
  MoreHorizontal,
  RefreshCw,
  Sparkles,
} from "lucide-react";
import { FaDev } from "react-icons/fa";


export const monthlyData = {
  currentMonth: "Juin 2025",
  billing: {
    totalRevenue: 2850000,
    invoicesSent: 45,
    invoicesPaid: 38,
    invoicesPending: 7,
    averagePaymentDelay: 18,
    recurringRevenue: 1950000,
    oneTimeRevenue: 900000,
  },
  productivity: {
    projectsActive: 23,
    projectsCompleted: 8,
    projectsDelayed: 3,
    averageProjectMargin: 32,
    billableHours: 3240,
    utilizationRate: 78,
    clientSatisfaction: 4.6,
  },
  resources: {
    totalEmployees: 45,
    availableConsultants: 12,
    onMission: 28,
    onBench: 5,
    utilizationTarget: 85,
    currentUtilization: 78,
    newHires: 3,
    turnover: 2,
  },
  partnerships: {
    salesforce: { deals: 12, revenue: 850000, growth: 15 },
    aws: { deals: 8, revenue: 620000, growth: 22 },
    microsoft: { deals: 15, revenue: 980000, growth: 8 },
    amplitude: { deals: 5, revenue: 280000, growth: 35 },
  },
  marketing: {
    totalFollowers: 45200,
    monthlyGrowth: 8.5,
    engagement: 4.2,
    reach: 125000,
    impressions: 890000,
    cpc: 0.85,
    cpm: 12.5,
    ctr: 2.8,
    roas: 4.2,
    leadGeneration: 156,
    conversionRate: 3.4,
    brandMentions: 89,
    sentimentScore: 78,
  },
  management: {
    strategicInitiatives: 12,
    completedInitiatives: 8,
    budgetUtilization: 87,
    teamPerformance: 8.2,
    stakeholderSatisfaction: 4.5,
    riskScore: 2.3,
    innovationIndex: 7.8,
    marketShare: 12.5,
  },
}


export const socialMediaData = [
  { platform: "LinkedIn", followers: 18500, growth: 12.3, engagement: 5.2, icon: Linkedin, color: "text-blue-600" },
  { platform: "Twitter", followers: 12800, growth: 8.7, engagement: 3.8, icon: Twitter, color: "text-sky-500" },
  { platform: "Instagram", followers: 8900, growth: 15.2, engagement: 6.1, icon: Instagram, color: "text-pink-500" },
  { platform: "Facebook", followers: 3200, growth: 2.1, engagement: 2.9, icon: Facebook, color: "text-blue-700" },
  { platform: "YouTube", followers: 1800, growth: 22.5, engagement: 8.4, icon: Youtube, color: "text-red-600" },
]


export const contentCalendar = [
  {
    date: "2025-06-25",
    type: "Blog",
    title: "L'IA dans la transformation digitale",
    platform: "Website + LinkedIn",
    status: "scheduled",
    engagement: "High",
  },
  {
    date: "2025-06-26",
    type: "Video",
    title: "Témoignage client - Projet Salesforce",
    platform: "YouTube + LinkedIn",
    status: "in-production",
    engagement: "Medium",
  },
  {
    date: "2025-06-27",
    type: "Post",
    title: "Tips Data Analytics",
    platform: "LinkedIn + Twitter",
    status: "draft",
    engagement: "High",
  },
  {
    date: "2025-06-28",
    type: "Webinar",
    title: "AWS Cloud Migration Best Practices",
    platform: "Zoom + LinkedIn",
    status: "scheduled",
    engagement: "Very High",
  },
  {
    date: "2025-06-30",
    type: "Newsletter",
    title: "Monthly Tech Insights",
    platform: "Email + Website",
    status: "draft",
    engagement: "Medium",
  },
]


export const marketPredictions = [
  {
    trend: "IA Générative en Entreprise",
    impact: "Very High",
    probability: 92,
    timeframe: "Q3 2025",
    recommendation: "Développer expertise GPT/LLM",
    source: "Gartner, McKinsey",
  },
  {
    trend: "Cloud-First Strategy",
    impact: "High",
    probability: 87,
    timeframe: "Q4 2025",
    recommendation: "Renforcer partenariats cloud",
    source: "IDC, Forrester",
  },
  {
    trend: "Data Mesh Architecture",
    impact: "Medium",
    probability: 74,
    timeframe: "2026",
    recommendation: "Former équipes sur Data Mesh",
    source: "ThoughtWorks",
  },
  {
    trend: "Sustainability Tech",
    impact: "High",
    probability: 89,
    timeframe: "Q3 2025",
    recommendation: "Intégrer solutions green IT",
    source: "Accenture, Deloitte",
  },
]


export const managementKPIs = [
  {
    category: "Strategic Execution",
    metrics: [
      { name: "Initiatives Completed", value: "8/12", trend: "up", target: "10/12" },
      { name: "Budget Utilization", value: "87%", trend: "up", target: "85%" },
      { name: "Timeline Adherence", value: "92%", trend: "down", target: "95%" },
    ],
  },
  {
    category: "Team Performance",
    metrics: [
      { name: "Overall Performance", value: "8.2/10", trend: "up", target: "8.5/10" },
      { name: "Employee Satisfaction", value: "4.3/5", trend: "stable", target: "4.5/5" },
      { name: "Retention Rate", value: "94%", trend: "up", target: "95%" },
    ],
  },
  {
    category: "Market Position",
    metrics: [
      { name: "Market Share", value: "12.5%", trend: "up", target: "15%" },
      { name: "Brand Recognition", value: "78%", trend: "up", target: "80%" },
      { name: "Competitive Index", value: "7.8/10", trend: "stable", target: "8.0/10" },
    ],
  },
]

export const departments = [
  { id: "admin", isEnabled : true, name: "Administration Générale", icon: Crown, color: "text-red-600" },
  { id: "ceo", isEnabled : true, name: "Direction Générale", icon: Crown, color: "text-amber-600" },
  { id: "finance", isEnabled : false, name: "Finance", icon: DollarSign, color: "text-green-600" },
  { id: "operations", isEnabled : false, name: "Opérations", icon: Settings, color: "text-blue-600" },
  { id: "hr", isEnabled : false, name: "Ressources Humaines", icon: UserCheck, color: "text-purple-600" },
  { id: "sales", isEnabled : false, name: "Commercial", icon: TrendingUp, color: "text-orange-600" },
  { id: "tech", isEnabled : true, name: "IT", icon: Monitor, color: "text-cyan-600" },
  { id: "marketing", isEnabled : false, name: "Marketing", icon: Megaphone, color: "text-pink-600" },
  { id: "management", isEnabled : false, name: "Management", icon: Briefcase, color: "text-indigo-600" },
]

export const sidebarItems = [
  { icon: Home, label: "Accueil", id: "accueil", active: false },
  { icon: MessageSquare, label: "Chat", id: "chat", active: false },
  { icon: Calendar, label: "Calendrier", id: "calendrier", active: false },
  { icon: Users, label: "Équipes", id: "equipes", active: false },
  { icon: Users2, label: "Collaborateurs", id: "collaborateurs", active: false },
  { icon: FolderOpen, label: "Projets", id: "projets", active: false },
  { icon: BookOpen, label: "Répertoire", id: "repertoire", active: false },
  { icon: FileText, label: "Documents", id: "documents", active: false },
  { icon: UserCheck, label: "RH", id: "rh", active: false },
  { icon: Building, label: "Entreprise", id: "entreprise", active: false },
  { icon: Settings, label: "Paramètres", id: "parametres", active: false },
  { icon: HelpCircle, label: "Aide", id: "aide", active: false },
]

// D&A Applications for the dock

export const dockApps = [
  {
    id: "daws",
    name: "DAWS",
    subtitle: "D&A WorkSpace",
    icon: Grid3X3,
    color: "bg-gradient-to-br from-blue-400 to-purple-500",
    iconColor: "text-white",
  },
  {
    id: "projects",
    name: "Gestion de Projets",
    subtitle: "D&A Gestion de Projets",
    icon: List,
    color: "bg-gradient-to-br from-orange-300 to-orange-500",
    iconColor: "text-white",
  },
  {
    id: "hr",
    name: "RH",
    subtitle: "D&A Ressource Humaine",
    icon: Users,
    color: "bg-gradient-to-br from-green-300 to-green-500",
    iconColor: "text-white",
  },
  {
    id: "marketing",
    name: "Marketing",
    subtitle: "D&A Marketing",
    icon: MegaphoneIcon,
    color: "bg-gradient-to-br from-pink-300 to-pink-500",
    iconColor: "text-white",
  },
  {
    id: "accounting",
    name: "Compta",
    subtitle: "D&A Comptabilite",
    icon: Calculator,
    color: "bg-gradient-to-br from-yellow-300 to-orange-400",
    iconColor: "text-white",
  },
  {
    id: "security",
    name: "Security",
    subtitle: "D&A Security",
    icon: ShieldCheck,
    color: "bg-gradient-to-br from-red-300 to-red-500",
    iconColor: "text-white",
  },
  {
    id: "portal",
    name: "Portail",
    subtitle: "Portail D&A",
    icon: BookOpen,
    color: "bg-gradient-to-br from-gray-400 to-gray-600",
    iconColor: "text-white",
  },
  {
    id: "break-room",
    name: "Salle de pause",
    subtitle: "Espace détente",
    icon: Coffee,
    color: "bg-gradient-to-br from-amber-400 to-amber-600",
    iconColor: "text-white",
  },
]


export const quickLinks = [
  { icon: MessageSquare, label: "Chat I.A.", color: "text-blue-600", isMain : true, href: "/app/chat", action: "chat" },
  { icon: Building, label: "Portail RH", color: "text-purple-600", isMain : true, href: "/app/hr", action: "hr-portal" },
  { icon: HelpCircle, label: "Support", color: "text-green-600", isMain : true, href: "/apps/helpcenter", action: "support" },
  { icon: FileText, label: "Documents", color: "text-orange-600", isMain : true, href: "/app/documents", action: "documents" },
  { icon: Calendar, label: "Calendrier", color: "text-blue-500", isMain : false, href: "/app/calendar", action: "calendar" },
  { icon: Phone, label: "Annuaire", color: "text-indigo-600", isMain : false, href: "/app/directory", action: "directory" },
  { icon: Monitor, label: "Portail", color: "text-cyan-600", isMain : false, href: "/app/portal", action: "portal" },
  { icon: Coffee, label: "Salle de pause", color: "text-pink-600", isMain : false, href: "/app/break-room", action: "break-room" },
]

// Employee data

export const employees = [
  {
    id: 1,
    name: "Marie Dubois",
    role: "Senior Data Scientist",
    department: "Data & Analytics",
    email: "marie.dubois@da-technologies.com",
    phone: "+33 1 23 45 67 89",
    location: "Paris",
    status: "En mission",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2022-03-15",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL"],
    currentProject: "Projet IA Prédictive - Client A",
    utilization: 95,
    performance: 4.8,
    certifications: ["AWS ML Specialty", "Google Cloud ML"],
    manager: "Thomas Martin",
    team: "IA & Machine Learning",
  },
  {
    id: 2,
    name: "Jean-Pierre Moreau",
    role: "Consultant Salesforce",
    department: "CRM & Expérience Client",
    email: "jp.moreau@da-technologies.com",
    phone: "+33 1 23 45 67 90",
    location: "Lyon",
    status: "Disponible",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2021-09-10",
    skills: ["Salesforce", "Apex", "Lightning", "Integration"],
    currentProject: null,
    utilization: 65,
    performance: 4.6,
    certifications: ["Salesforce Admin", "Platform Developer I"],
    manager: "Sophie Laurent",
    team: "Salesforce Excellence",
  },
  {
    id: 3,
    name: "Sarah Chen",
    role: "Architecte Cloud",
    department: "Cloud & Intégration",
    email: "sarah.chen@da-technologies.com",
    phone: "+33 1 23 45 67 91",
    location: "Paris",
    status: "En mission",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2020-11-22",
    skills: ["AWS", "Azure", "Kubernetes", "DevOps"],
    currentProject: "Migration Cloud - Enterprise B",
    utilization: 88,
    performance: 4.9,
    certifications: ["AWS Solutions Architect", "Azure Expert"],
    manager: "David Kim",
    team: "Cloud Architecture",
  },
  {
    id: 4,
    name: "Alexandre Petit",
    role: "Consultant BI",
    department: "Data & Analytics",
    email: "alexandre.petit@da-technologies.com",
    phone: "+33 1 23 45 67 92",
    location: "Toulouse",
    status: "En formation",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2023-01-08",
    skills: ["Power BI", "Tableau", "SQL", "DAX"],
    currentProject: null,
    utilization: 0,
    performance: 4.2,
    certifications: ["Microsoft Power BI"],
    manager: "Marie Dubois",
    team: "Business Intelligence",
  },
  {
    id: 5,
    name: "Camille Rodriguez",
    role: "UX/UI Designer",
    department: "Transformation Digitale",
    email: "camille.rodriguez@da-technologies.com",
    phone: "+33 1 23 45 67 93",
    location: "Paris",
    status: "En mission",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2022-07-03",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    currentProject: "Refonte UX - Application Mobile",
    utilization: 92,
    performance: 4.7,
    certifications: ["Google UX Design", "Adobe Certified"],
    manager: "Lucas Blanc",
    team: "Digital Experience",
  },
  {
    id: 6,
    name: "Thomas Martin",
    role: "Lead Data Scientist",
    department: "Data & Analytics",
    email: "thomas.martin@da-technologies.com",
    phone: "+33 1 23 45 67 94",
    location: "Paris",
    status: "En mission",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2019-05-12",
    skills: ["Python", "R", "Deep Learning", "MLOps"],
    currentProject: "Plateforme ML - Groupe C",
    utilization: 85,
    performance: 4.9,
    certifications: ["AWS ML Specialty", "Databricks Certified"],
    manager: "CEO",
    team: "IA & Machine Learning",
  },
]


export  const teamStats = {
  totalEmployees: 45,
  onMission: 28,
  available: 12,
  inTraining: 3,
  onLeave: 2,
  averageUtilization: 78,
  averagePerformance: 4.6,
  newHiresThisMonth: 3,
  departmentDistribution: {
    "Data & Analytics": 15,
    "Transformation Digitale": 12,
    "CRM & Expérience Client": 8,
    "Cloud & Intégration": 6,
    Marketing: 4,
  },
}


