import { AppEmployee } from "../../apis/employee";



export const mockData_departments_en: string[] = [
  "All Departments",
  "Executive",
  "Marketing",
  "Sales",
  "Engineering",
  "Product",
  "Design",
  "Customer Support",
  "Human Resources",
  "Finance",
  "Legal",
]

export const mockData_departments_fr: string[] = [
  "Tous les départements",
  "Exécutif",
  "Marketing",
  "Ventes",
  "Ingénierie",
  "Produit",
  "Conception",
  "Support Client",
  "Ressources Humaines",
  "Finances",
  "Juridique",
]

export const mockData_departments_ar: string[] = [
  "جميع الأقسام",
  "تنفيذي",
  "تسويق",
  "مبيعات",
  "هندسة",
  "منتج",
  "تصميم",
  "دعم العملاء",
  "الموارد البشرية",
  "مالية",
  "قانونية",
];


// Localized project data based on the current locale
export const mockData_departments: { en: string[], fr: string[], ar: string[] } = {
  en: mockData_departments_en ,
  fr: mockData_departments_fr ,
  ar: mockData_departments_ar ,
};


export const mockData_employees_en: AppEmployee[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    title: "Chief Executive Officer",
    department: "Executive",
    location: "San Francisco",
    email: "sarah.johnson@company.com",
    phone: "(+212) 06 123-4567",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238645_11475210.jpg-lU8bOe6TLt5Rv51hgjg8NT8PsDBmvN.jpeg",
  },
  {
    id: 2,
    name: "Michael Chen",
    title: "Chief Operating Officer",
    department: "Executive",
    location: "San Francisco",
    email: "michael.chen@company.com",
    phone: "(+212) 06 234-5678",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238208_11475222.jpg-poEIzVHAGiIfMFQ7EiF8PUG1u0Zkzz.jpeg",
  },
  {
    id: 3,
    name: "Alex Rivera",
    title: "Chief Technology Officer",
    department: "Engineering",
    location: "San Francisco",
    email: "alex.rivera@company.com",
    phone: "(+212) 06 345-6789",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dd.jpg-4MCwPC2Bec6Ume26Yo1kao3CnONxDg.jpeg",
  },
  {
    id: 4,
    name: "Jennifer Smith",
    title: "Chief Marketing Officer",
    department: "Marketing",
    location: "New York",
    email: "jennifer.smith@company.com",
    phone: "(+212) 06 456-7890",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 5,
    name: "David Wilson",
    title: "Chief Financial Officer",
    department: "Finance",
    location: "Chicago",
    email: "david.wilson@company.com",
    phone: "(+212) 06 567-8901",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9334178.jpg-Y74tW6XFO68g7N36SE5MSNDNVKLQ08.jpeg",
  },
  {
    id: 6,
    name: "Lisa Brown",
    title: "Chief People Officer",
    department: "Human Resources",
    location: "San Francisco",
    email: "lisa.brown@company.com",
    phone: "(+212) 06 678-9012",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5295.jpg-fLw0wGGZp8wuTzU5dnyfjZDwAHN98a.jpeg",
  },
  {
    id: 7,
    name: "Robert Davis",
    title: "Senior Software Engineer",
    department: "Engineering",
    location: "Seattle",
    email: "robert.davis@company.com",
    phone: "(+212) 06 789-0123",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 8,
    name: "Emily Rodriguez",
    title: "Product Manager",
    department: "Product",
    location: "San Francisco",
    email: "emily.rodriguez@company.com",
    phone: "(+212) 06 890-1234",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/27470341_7294795.jpg-XE0zf7R8tk4rfA1vm4fAHeZ1QoVEOo.jpeg",
  },
  {
    id: 9,
    name: "Jessica Chen",
    title: "UX Designer",
    department: "Design",
    location: "New York",
    email: "jessica.chen@company.com",
    phone: "(+212) 06 901-2345",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/799.jpg-0tEi4Xvg5YsFoGoQfQc698q4Dygl1S.jpeg",
  },
]

export const mockData_employees_fr: AppEmployee[] = [
  {
    id: 1,
    name: "Sarah Joubert",
    title: "Directrice Générale",
    department: "Exécutif",
    location: "San Francisco",
    email: "sarah.johnson@company.com",
    phone: "(+212) 06 123-4567",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238645_11475210.jpg-lU8bOe6TLt5Rv51hgjg8NT8PsDBmvN.jpeg",
  },
  {
    id: 2,
    name: "Michel Chen",
    title: "Directeur des Opérations",
    department: "Exécutif",
    location: "San Francisco",
    email: "michael.chen@company.com",
    phone: "(+212) 06 234-5678",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238208_11475222.jpg-poEIzVHAGiIfMFQ7EiF8PUG1u0Zkzz.jpeg",
  },
  {
    id: 3,
    name: "Alexandre Rivera",
    title: "Directeur Technique",
    department: "Ingénierie",
    location: "San Francisco",
    email: "alex.rivera@company.com",
    phone: "(+212) 06 345-6789",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dd.jpg-4MCwPC2Bec6Ume26Yo1kao3CnONxDg.jpeg",
  },
  {
    id: 4,
    name: "Jeanne Dubois",
    title: "Directrice Marketing",
    department: "Marketing",
    location: "New York",
    email: "jennifer.smith@company.com",
    phone: "(+212) 06 456-7890",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 5,
    name: "David Martin",
    title: "Directeur Financier",
    department: "Finances",
    location: "Chicago",
    email: "david.wilson@company.com",
    phone: "(+212) 06 567-8901",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9334178.jpg-Y74tW6XFO68g7N36SE5MSNDNVKLQ08.jpeg",
  },
  {
    id: 6,
    name: "Lucie Moreau",
    title: "Directrice des Ressources Humaines",
    department: "Ressources Humaines",
    location: "San Francisco",
    email: "lisa.brown@company.com",
    phone: "(+212) 06 678-9012",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5295.jpg-fLw0wGGZp8wuTzU5dnyfjZDwAHN98a.jpeg",
  },
  {
    id: 7,
    name: "Robert Lefebvre",
    title: "Ingénieur Logiciel Senior",
    department: "Ingénierie",
    location: "Seattle",
    email: "robert.davis@company.com",
    phone: "(+212) 06 789-0123",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 8,
    name: "Émilie Rodriguez",
    title: "Chef de Produit",
    department: "Produit",
    location: "San Francisco",
    email: "emily.rodriguez@company.com",
    phone: "(+212) 06 890-1234",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/27470341_7294795.jpg-XE0zf7R8tk4rfA1vm4fAHeZ1QoVEOo.jpeg",
  },
  {
    id: 9,
    name: "Jessica Dupont",
    title: "Designer UX",
    department: "Conception",
    location: "New York",
    email: "jessica.chen@company.com",
    phone: "(+212) 06 901-2345",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/799.jpg-0tEi4Xvg5YsFoGoQfQc698q4Dygl1S.jpeg",
  },
]

export const mockData_employees_ar: AppEmployee[] = [
  {
    id: 1,
    name: "سارة جونسون",
    title: "الرئيس التنفيذي",
    department: "تنفيذي",
    location: "سان فرانسيسكو",
    email: "sarah.johnson@company.com",
    phone: "(+212) 06 123-4567",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238645_11475210.jpg-lU8bOe6TLt5Rv51hgjg8NT8PsDBmvN.jpeg",
  },
  {
    id: 2,
    name: "مايكل تشن",
    title: "مدير العمليات التنفيذي",
    department: "تنفيذي",
    location: "سان فرانسيسكو",
    email: "michael.chen@company.com",
    phone: "(+212) 06 234-5678",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/375238208_11475222.jpg-poEIzVHAGiIfMFQ7EiF8PUG1u0Zkzz.jpeg",
  },
  {
    id: 3,
    name: "أليكس ريفيرا",
    title: "المدير التقني",
    department: "هندسة",
    location: "سان فرانسيسكو",
    email: "alex.rivera@company.com",
    phone: "(+212) 06 345-6789",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dd.jpg-4MCwPC2Bec6Ume26Yo1kao3CnONxDg.jpeg",
  },
  {
    id: 4,
    name: "جينيفر سميث",
    title: "مدير التسويق التنفيذي",
    department: "تسويق",
    location: "نيويورك",
    email: "jennifer.smith@company.com",
    phone: "(+212) 06 456-7890",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 5,
    name: "ديفيد ويلسون",
    title: "المدير المالي",
    department: "مالية",
    location: "شيكاغو",
    email: "david.wilson@company.com",
    phone: "(+212) 06 567-8901",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9334178.jpg-Y74tW6XFO68g7N36SE5MSNDNVKLQ08.jpeg",
  },
  {
    id: 6,
    name: "ليزا براون",
    title: "مدير شؤون الموظفين",
    department: "الموارد البشرية",
    location: "سان فرانسيسكو",
    email: "lisa.brown@company.com",
    phone: "(+212) 06 678-9012",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5295.jpg-fLw0wGGZp8wuTzU5dnyfjZDwAHN98a.jpeg",
  },
  {
    id: 7,
    name: "روبرت ديفيس",
    title: "مهندس برمجيات أول",
    department: "هندسة",
    location: "سياتل",
    email: "robert.davis@company.com",
    phone: "(+212) 06 789-0123",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/9720029.jpg-Yf9h2a3kT7rYyCb648iLIeHThq5wEy.jpeg",
  },
  {
    id: 8,
    name: "إيميلي رودريغيز",
    title: "مدير منتج",
    department: "منتج",
    location: "سان فرانسيسكو",
    email: "emily.rodriguez@company.com",
    phone: "(+212) 06 890-1234",
    avatar:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/27470341_7294795.jpg-XE0zf7R8tk4rfA1vm4fAHeZ1QoVEOo.jpeg",
  },
  {
    id: 9,
    name: "جيسيكا تشن",
    title: "مصمم تجربة المستخدم",
    department: "تصميم",
    location: "نيويورك",
    email: "jessica.chen@company.com",
    phone: "(+212) 06 901-2345",
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/799.jpg-0tEi4Xvg5YsFoGoQfQc698q4Dygl1S.jpeg",
  },
]


// Localized employee data based on the current locale
export const mockData_employees: { en: AppEmployee[], fr: AppEmployee[], ar: AppEmployee[] } = {
    en: mockData_employees_en ,
    fr: mockData_employees_fr ,
    ar: mockData_employees_ar ,
};
