
// Mock Data based on the provided image
export const projectsMockData  = [
  {
    id: 1,
    name: "EBS",
    avatarUrl: "https://www.ebs-energie.com/wp-content/uploads/logo-ebs-energie-baseline.svg",
    team: "Sécurité Cloud",
    progress: 85,
    status: "En cours",
    dueDate: "15 sept. 2025",
    priority: "Haute",
    collaborators: [
      { name: "Khadija", allocation: 70, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Khadija.png" },
      { name: "Rania", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Rania.png" },
      { name: "Abir", allocation: 80, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Abir.png" },
      { name: "Hatim Bekkar", allocation: 80, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Hatim_Bekkar.png" },
      { name: "Yahya", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Yahya.png" },
      { name: "Ayman Lahmidi", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Ayman_Lahmidi.png" },
      { name: "Abdessamad", allocation: 80, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Abdessamad.png" },
      { name: "Ayoub Dahbi", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Ayoub_Dahbi.png" },
    ],
  },
  {
    id: 2,
    name: "SONERGIA",
    avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logos/SONERGIA.png",
    team: "Conformité RGPD",
    progress: 45,
    status: "En cours",
    dueDate: "30 oct. 2025",
    priority: "Moyenne",
    collaborators: [
        { name: "Houda", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Houda.png" },
        { name: "Zineb", allocation: 30, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Zineb.png" },
        { name: "Mohamed amine Rahmi", allocation: 80, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Mohamed_amine_Rahmi.png" },
        { name: "Hamza Chaoui", allocation: 90, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Hamza_Chaoui.png" },
        { name: "Elmustapha elgarni", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Elmustapha_elgarni.png" },
        { name: "OUASSIM EL YAZIDI", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/OUASSIM_EL_YAZIDI.png" },
        { name: "Amina Benabdlekrim", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Amina_Benabdlekrim.png" },
        { name: "Tajeddine", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Tajeddine.png" },
        { name: "hassan jabrane", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/hassan_jabrane.png" },
        { name: "Elmasrioui mohamed amine", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Elmasrioui_mohamed_amine.png" },
        { name: "Eljouali ali", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Eljouali_ali.png" },
        { name: "Sasioui abdelmola", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Sasioui_abdelmola.png" },
        { name: "Abdelbarie mati", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Abdelbarie_mati.png" },
        { name: "bakkou adnane", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/bakkou_adnane.png" },
        { name: "Ahmed Reda", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Ahmed_Reda.png" },
    ],
  },
  {
    id: 3,
    name: "AXA CIMA",
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/AXA_Logo.svg",
    team: "Audit Interne",
    progress: 95,
    status: "Finalisation",
    dueDate: "30 juil. 2025",
    priority: "Haute",
    collaborators: [
        { name: "Houda", allocation: 10, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Houda.png" },
        { name: "Oumaima Bensdira", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Oumaima_Bensdira.png" },
        { name: "Zibouli mohamed", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Zibouli_mohamed.png" },
        { name: "Marouane el bouri", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Marouane_el_bouri.png" },
        { name: "FZ Jasour", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/FZ_Jasour.png" },
        { name: "Salahedine", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Salahedine.png" },
        { name: "Omar", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Omar.png" },
        { name: "Soukaina", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Soukaina.png" },
        { name: "Hicham", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Hicham.png" },
    ],
  },
  {
    id: 4,
    name: "INJAZ",
    avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logos/INJAZ.png",
    team: "Développement Sécurisé",
    progress: 60,
    status: "En cours",
    dueDate: "10 nov. 2025",
    priority: "Moyenne",
    collaborators: [
        { name: "Oumayma", allocation: 90, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Oumayma.png" },
        { name: "Hamza Chaoui", allocation: 10, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Hamza_Chaoui.png" },
        { name: "Hatim Bekkar", allocation: 20, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Hatim_Bekkar.png" },
        { name: "Stagiaire 1", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Stagiaire_1.png" },
        { name: "Stagiaire 2", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Stagiaire_2.png" },
    ],
  },
  {
    id: 5,
    name: "AGMA",
    avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logos/AGMA.png",
    team: "Gestion des Risques",
    progress: 30,
    status: "Planifié",
    dueDate: "15 déc. 2025",
    priority: "Faible",
    collaborators: [
        { name: "Oumayma", allocation: 20, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Oumayma.png" },
        { name: "Amine Rahmi", allocation: 20, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Amine_Rahmi.png" },
        { name: "Dev à définir", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Dev_a_definir.png" },
        { name: "oussama", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/oussama.png" },
        { name: "Mouhcine Taryaoui", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Mouhcine_Taryaoui.png" },
    ],
  },
  {
    id: 6,
    name: "ANRAC",
    avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logos/ANRAC.png",
    team: "Opérations de Sécurité",
    progress: 50,
    status: "En cours",
    dueDate: "01 oct. 2025",
    priority: "Haute",
    collaborators: [
        { name: "Samia", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Samia.png" },
        { name: "Nada", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Nada.png" },
        { name: "Najlae", allocation: 100, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Najlae.png" },
        { name: "Amina Anechad", allocation: 50, avatarUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/users/Amina_Anechad.png" },
    ],
  },
]
